#setting:
#  ip:
#    prefer-net-mask:
#
#context:
#  initializer:
#    classes: com.parade.paradeproject.config.initializer.IpAddressApplicationContextInitializer, com.parade.paradeproject.config.initializer.EurekaIpAddressApplicationContextInitializer
    
server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      
 
spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    
  datasource:
    url: jdbc:mysql://parademysqldb.cvh921nshuu2.ap-northeast-1.rds.amazonaws.com:3306/parade?characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: paradedb
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  data:
    jdbc:
      repositories:
        enabled: false


logging:
  level:
    org:
      hibernate:
        SQL: debug